In [1]:
import pandas as pd

base =pd.read_csv('iris.csv')
previsores = base.iloc[:,0:4].values
classe = base.iloc[:,4].values

In [10]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

LabelEncoder = LabelEncoder()
classe = LabelEncoder.fit_transform(classe)
classe_dummy = np_utils.to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [11]:
from sklearn.model_selection import train_test_split

previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe_dummy, test_size=0.25)

In [13]:
import tensorflow as tf
import tensorflow.keras
from tensorflow.keras.models import Sequential


classificador = Sequential()
classificador.add(tf.keras.layers.Dense(units = 4, activation = 'relu', input_dim = 4))
classificador.add(tf.keras.layers.Dense(units = 4, activation = 'relu'))
classificador.add(tf.keras.layers.Dense(units = 3, activation = 'softmax'))
classificador.compile(optimizer= 'adam', loss='categorical_crossentropy', metrics='categorical_accuracy')
classificador.fit(previsores_treinamento, classe_treinamento, batch_size=10,epochs=1000)

Epoch 1/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.0916 - categorical_accuracy: 0.3571
Epoch 2/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.0515 - categorical_accuracy: 0.3571
Epoch 3/1000
12/12 [==============================] - 0s 1ms/step - loss: 1.0166 - categorical_accuracy: 0.3571
Epoch 4/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.9866 - categorical_accuracy: 0.3571
Epoch 5/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.9598 - categorical_accuracy: 0.3571
Epoch 6/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.9370 - categorical_accuracy: 0.3571
Epoch 7/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.9116 - categorical_accuracy: 0.4018
Epoch 8/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.8877 - categorical_accuracy: 0.5357
Epoch 9/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.8651 - categorical_accuracy:

In [14]:
resultado = classificador.evaluate(previsores_teste, classe_teste)
resultado

2/2 [==============================] - 0s 3ms/step - loss: 0.1304 - categorical_accuracy: 0.9211


[0.13042299449443817, 0.9210526347160339]

In [16]:
previsores = classificador.predict(previsores_teste)
previsores

2/2 [==============================] - 0s 2ms/step


array([[2.3583432e-05, 9.9819750e-01, 1.7789321e-03],
       [1.5112566e-21, 2.6898152e-07, 9.9999976e-01],
       [7.8704154e-08, 9.6173716e-01, 3.8262792e-02],
       [4.7052472e-07, 2.1027638e-01, 7.8972310e-01],
       [5.2471856e-13, 7.3568888e-05, 9.9992645e-01],
       [9.9767238e-01, 1.7017621e-03, 6.2582933e-04],
       [9.9767238e-01, 1.7017621e-03, 6.2582933e-04],
       [9.9767238e-01, 1.7017621e-03, 6.2582933e-04],
       [9.9767238e-01, 1.7017621e-03, 6.2582933e-04],
       [1.7481914e-06, 9.9926275e-01, 7.3542289e-04],
       [5.0609482e-15, 2.0471169e-05, 9.9997950e-01],
       [9.9767238e-01, 1.7017621e-03, 6.2582933e-04],
       [7.3359241e-17, 9.3590126e-05, 9.9990642e-01],
       [8.3636857e-09, 1.0072663e-01, 8.9927334e-01],
       [3.0997829e-11, 8.2628801e-02, 9.1737115e-01],
       [1.4100712e-13, 2.3672667e-04, 9.9976331e-01],
       [4.1334282e-08, 7.9488862e-01, 2.0511138e-01],
       [9.9767238e-01, 1.7017621e-03, 6.2582933e-04],
       [9.0686024e-14, 1.110

In [21]:
import numpy as np

previsoes = (previsores > 0.5)
classe_teste2 = [np.argmax(t) for t in classe_teste]
previsoes2 = [np.argmax(t) for t in previsoes]

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(previsoes2, classe_teste2)
matriz

array([[12,  0,  0],
       [ 0,  9,  2],
       [ 0,  1, 14]], dtype=int64)

In [22]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [23]:

base = pd.read_csv('iris.csv')
previsores = base.iloc[:, 0:4].values
classe = base.iloc[:, 4].values
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
classe = labelencoder.fit_transform(classe)
classe_dummy = np_utils.to_categorical(classe)

In [24]:
def criar_rede():
    classificador = Sequential()
    classificador.add(Dense(units = 4, activation = 'relu', input_dim = 4))
    classificador.add(Dense(units = 4, activation = 'relu'))
    classificador.add(Dense(units = 3, activation = 'softmax'))
    classificador.compile(optimizer = 'adam', loss = 'categorical_crossentropy',
                          metrics = ['categorical_accuracy'])
    return classificador

In [25]:

classificador = KerasClassifier(build_fn = criar_rede,
                                epochs = 1000,
                                batch_size = 10)
resultados = cross_val_score(estimator = classificador,
                             X = previsores, y = classe,
                             cv = 10, scoring = 'accuracy')

Epoch 1/1000


C:\Users\bruno\AppData\Local\Temp\ipykernel_5692\3365260119.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classificador = KerasClassifier(build_fn = criar_rede,


14/14 [==============================] - 0s 1ms/step - loss: 2.6003 - categorical_accuracy: 0.3704
Epoch 2/1000
14/14 [==============================] - 0s 2ms/step - loss: 2.4280 - categorical_accuracy: 0.3704
Epoch 3/1000
14/14 [==============================] - 0s 1ms/step - loss: 2.2581 - categorical_accuracy: 0.3704
Epoch 4/1000
14/14 [==============================] - 0s 1ms/step - loss: 2.1071 - categorical_accuracy: 0.3704
Epoch 5/1000
14/14 [==============================] - 0s 1ms/step - loss: 1.9709 - categorical_accuracy: 0.3704
Epoch 6/1000
14/14 [==============================] - 0s 2ms/step - loss: 1.8493 - categorical_accuracy: 0.3704
Epoch 7/1000
14/14 [==============================] - 0s 1ms/step - loss: 1.7422 - categorical_accuracy: 0.3704
Epoch 8/1000
14/14 [==============================] - 0s 1ms/step - loss: 1.6508 - categorical_accuracy: 0.3704
Epoch 9/1000
14/14 [==============================] - 0s 1ms/step - loss: 1.5699 - categorical_accuracy: 0.3704
Epoch

In [26]:
media = resultados.mean()
desvio = resultados.std()

In [27]:
media

0.8600000000000001

In [28]:
desvio

0.3032417444145109

In [30]:
IC = (media + desvio, media - desvio, media + desvio*2, media - desvio*2)
IC

(1.1632417444145111, 0.5567582555854892, 1.466483488829022, 0.2535165111709783)